TEZ-4040. Upgrade RoaringBitmap version to avoid NoSuchMethodError (Jonathan Eagles via kshukla)
(cherry picked from commit f9da6bbb83fcca59eff7a721f5d5f9e511f23f50)